# Generated by Django 6.0.2 on 2026-02-18 12:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    replaces = [('home', '0007_alter_sectionpage_rows')]

    dependencies = [
        ("govuk", "0005_convert_homepage_to_sectionpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionpage",
            name="rows",
            field=wagtail.fields.StreamField(
                [("row", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading for this row section.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 120, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ul", "ol"],
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional button text.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional URL for the button, for example /apply or https://example.gov.uk/apply.",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("text", 2),
                                ("link_text", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {"icon": "doc-full", "label": "Card"},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "help_text": "Add between 1 and 15 cards in this row.",
                            "max_num": 15,
                            "min_num": 1,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("cards", 6)]],
                        {"icon": "placeholder", "label": "Row section"},
                    ),
                },
                help_text="Add one or more row sections. Each row can contain up to 15 cards.",
            ),
        ),
    ]
