# Generated by Django 6.0.2 on 2026-02-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0009_alter_sectionpage_enable_combined_service_navigation_and_hero_styling')]

    dependencies = [
        (
            "govuk",
            "0007_alter_sectionpage_rows",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionpage",
            name="enable_combined_service_navigation_and_hero_styling",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this page uses a combined service navigation and hero styling.",
                verbose_name="Enable combined service navigation and hero styling",
            ),
        ),
    ]
