# Generated by Django 6.0.2 on 2026-02-18 16:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0012_contentpage_enable_combined_service_navigation_and_hero_styling_and_more')]

    dependencies = [
        ("govuk", "0010_phasebannersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionpage",
            name="enable_hero_styling",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this page uses hero styling.",
                verbose_name="Enable hero styling",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="enable_combined_service_navigation_and_hero_styling",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this page uses a combined service navigation and hero styling.",
                verbose_name="Enable combined service navigation and hero styling",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="enable_hero_styling",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this page uses hero styling.",
                verbose_name="Enable hero styling",
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="hero_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="hero_title",
            field=models.CharField(
                blank=True,
                help_text="Optional hero heading. If blank, the page title is used.",
                max_length=255,
            ),
        ),
    ]
