# Generated by Django 6.0.2 on 2026-02-19 13:27

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0014_govuktag_alter_sectionpage_rows_contentpagetag_and_more')]


    dependencies = [
        ('govuk', '0013_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovukTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='rows',
            field=wagtail.fields.StreamField([('row', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading for this row section.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional button text.', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional URL for the button, for example /apply or https://example.gov.uk/apply.', 'max_length': 500, 'required': False}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukTag',), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Optional tags for this card.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 2), ('link_text', 3), ('link_url', 4), ('tags', 6)]], {'icon': 'doc-full', 'label': 'Card'}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Add between 1 and 15 cards in this row.', 'max_num': 15, 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 8)]], {'icon': 'placeholder', 'label': 'Row section'})}, help_text='Add one or more row sections. Each row can contain up to 15 cards.'),
        ),
        migrations.CreateModel(
            name='ContentPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.contentpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.ContentPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='SectionPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.sectionpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.SectionPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
    ]
