# Generated by Django 6.0.2 on 2026-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0018_contentdiscoverysource_disable_tls_verification')]


    dependencies = [
        ('govuk', '0017_externalcontentitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdiscoverysource',
            name='disable_tls_verification',
            field=models.BooleanField(default=False, help_text='When enabled, certificate verification is skipped for this source.', verbose_name='Disable TLS verification'),
        ),
    ]
