# Generated by Django 6.0.2 on 2026-02-19 17:03

import wagtail.fields
from django.db import migrations


def copy_default_tags_to_stream(apps, schema_editor):
    ContentDiscoverySource = apps.get_model("govuk", "ContentDiscoverySource")

    for source in ContentDiscoverySource.objects.all():
        tag_ids = list(source.default_tags.values_list("id", flat=True))
        source.default_tags_stream = [
            {
                "type": "tag",
                "value": tag_id,
            }
            for tag_id in tag_ids
        ]
        source.save(update_fields=["default_tags_stream"])


class Migration(migrations.Migration):
    replaces = [('home', '0019_remove_contentdiscoverysource_default_tags_and_more')]


    dependencies = [
        ('govuk', '0018_contentdiscoverysource_disable_tls_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdiscoverysource",
            name="default_tags_stream",
            field=wagtail.fields.StreamField([('tag', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukTag',), {'required': False})}, help_text='Optional tags to apply to discovered content from this source.'),
        ),
        migrations.RunPython(
            code=copy_default_tags_to_stream,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="contentdiscoverysource",
            name="default_tags",
        ),
        migrations.RenameField(
            model_name="contentdiscoverysource",
            old_name="default_tags_stream",
            new_name="default_tags",
        ),
    ]
