# Generated by Django 6.0.2 on 2026-02-19 17:08

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


def copy_existing_external_content_tags(apps, schema_editor):
    ExternalContentItem = apps.get_model("govuk", "ExternalContentItem")
    ExternalContentItemTag = apps.get_model("govuk", "ExternalContentItemTag")

    rows = []
    for item in ExternalContentItem.objects.all():
        tag_ids = list(item.tags.values_list("id", flat=True))
        for tag_id in tag_ids:
            rows.append(
                ExternalContentItemTag(
                    content_object_id=item.id,
                    tag_id=tag_id,
                )
            )

    if rows:
        ExternalContentItemTag.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):
    replaces = [('home', '0020_externalcontentitemtag_and_more')]


    dependencies = [
        ('govuk', '0019_remove_contentdiscoverysource_default_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContentItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.externalcontentitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_content_item_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=copy_existing_external_content_tags,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="externalcontentitem",
            name="tags",
        ),
        migrations.AddField(
            model_name="externalcontentitem",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.ExternalContentItemTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
    ]
