# Generated by Django 6.0.2 on 2026-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0022_taglistingspage_enable_source_filter_and_more')]


    dependencies = [
        ('govuk', '0021_externalcontentlistingpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglistingspage',
            name='enable_source_filter',
            field=models.BooleanField(default=False, help_text='Show a source filter control above the listings.', verbose_name='Enable source filter'),
        ),
        migrations.AddField(
            model_name='taglistingspage',
            name='enable_tag_filter',
            field=models.BooleanField(default=False, help_text='Show a tag filter control above the listings.', verbose_name='Enable tag filter'),
        ),
    ]
