# Generated by Django 6.0.2 on 2026-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0023_contentpage_enable_free_text_heading_navigation_and_more')]


    dependencies = [
        ('govuk', '0022_taglistingspage_enable_source_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='enable_free_text_heading_navigation',
            field=models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='enable_free_text_heading_navigation',
            field=models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation'),
        ),
        migrations.AddField(
            model_name='taglistingspage',
            name='enable_free_text_heading_navigation',
            field=models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation'),
        ),
    ]
