# Generated by Django 6.0.2 on 2026-02-21 21:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('home', '0024_authenticatedredirectsettings_and_more')]


    dependencies = [
        ('govuk', '0023_contentpage_enable_free_text_heading_navigation_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedRedirectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Authenticated user redirects',
                'verbose_name_plural': 'Authenticated user redirects',
            },
        ),
        migrations.CreateModel(
            name='AuthenticatedRedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('source_path', models.CharField(help_text='Path to match, for example /.', max_length=255)),
                ('destination_path', models.CharField(help_text='Path to redirect to, for example /dashboard.', max_length=500)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='govuk.authenticatedredirectsettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('settings', 'source_path'), name='home_auth_redirect_source_path_unique_per_site')],
            },
        ),
    ]
