# Generated by Django 6.0.2 on 2026-02-21 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("govuk", "0001_initial")]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('feedback_type', models.CharField(choices=[('correction', 'Correction'), ('feature_suggestion', 'Feature suggestion'), ('bug_report', 'Bug report'), ('content_request', 'Content request'), ('general', 'General feedback'), ('other', 'Other')], default='general', max_length=40)),
                ('comments', models.TextField()),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('is_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
