# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


TABLE_RENAMES = [
    ("home_authenticatedredirectrule", "govuk_authenticatedredirectrule"),
    ("home_authenticatedredirectsettings", "govuk_authenticatedredirectsettings"),
    ("home_contentdiscoverysettings", "govuk_contentdiscoverysettings"),
    ("home_contentdiscoverysource", "govuk_contentdiscoverysource"),
    ("home_contentpage", "govuk_contentpage"),
    ("home_contentpagetag", "govuk_contentpagetag"),
    ("home_externalcontentitem", "govuk_externalcontentitem"),
    ("home_externalcontentitemtag", "govuk_externalcontentitemtag"),
    ("home_footersettings", "govuk_footersettings"),
    ("home_govuktag", "govuk_govuktag"),
    ("home_phasebannersettings", "govuk_phasebannersettings"),
    ("home_sectionpage", "govuk_sectionpage"),
    ("home_sectionpagetag", "govuk_sectionpagetag"),
    ("home_taglistingspage", "govuk_taglistingspage"),
    ("home_taglistingspagetag", "govuk_taglistingspagetag"),
]

MOVED_MODELS = [
    "authenticatedredirectrule",
    "authenticatedredirectsettings",
    "contentdiscoverysettings",
    "contentdiscoverysource",
    "contentpage",
    "contentpagetag",
    "externalcontentitem",
    "externalcontentitemtag",
    "footersettings",
    "govuktag",
    "phasebannersettings",
    "sectionpage",
    "sectionpagetag",
    "taglistingspage",
    "taglistingspagetag",
]


def _rename_legacy_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    quote_name = schema_editor.quote_name

    for old_name, new_name in TABLE_RENAMES:
        if old_name not in existing_tables or new_name in existing_tables:
            continue
        schema_editor.execute(
            f"ALTER TABLE {quote_name(old_name)} RENAME TO {quote_name(new_name)}"
        )
        existing_tables.remove(old_name)
        existing_tables.add(new_name)


def _repoint_content_type_references(apps, db_alias, *, old_id: int, new_id: int):
    for model in apps.get_models():
        opts = model._meta
        if opts.proxy:
            continue

        for field in opts.local_fields:
            remote_field = getattr(field, "remote_field", None)
            target_model = getattr(remote_field, "model", None)
            target_meta = getattr(target_model, "_meta", None)
            if not target_meta:
                continue
            if target_meta.app_label != "contenttypes":
                continue
            if target_meta.model_name != "contenttype":
                continue

            model._default_manager.using(db_alias).filter(
                **{field.attname: old_id}
            ).update(**{field.attname: new_id})


def _migrate_content_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")

    for model_name in MOVED_MODELS:
        old_ct = (
            ContentType.objects.using(db_alias)
            .filter(app_label="home", model=model_name)
            .first()
        )
        if old_ct is None:
            continue

        new_ct = (
            ContentType.objects.using(db_alias)
            .filter(app_label="govuk", model=model_name)
            .first()
        )
        if new_ct is not None and new_ct.pk != old_ct.pk:
            _repoint_content_type_references(
                apps, db_alias, old_id=new_ct.pk, new_id=old_ct.pk
            )
            new_ct.delete()

        old_ct.app_label = "govuk"
        old_ct.save(update_fields=["app_label"])


def rename_home_tables_to_govuk(apps, schema_editor):
    _rename_legacy_tables(apps, schema_editor)
    _migrate_content_types(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("govuk", "0024_authenticatedredirectsettings_and_more"),
        ("govuk", "0025_feedback"),
    ]

    operations = [
        migrations.RunPython(rename_home_tables_to_govuk, migrations.RunPython.noop),
    ]
