"""
Django settings for govuk project.

Generated by 'django-admin startproject' using Django {{ django_version }}.

For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""

import logging
import os
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

SITE_ID = 1
logger = logging.getLogger(__name__)


def _parse_admin_user_emails(raw_emails: str | None) -> list[str]:
    emails: list[str] = []
    seen: set[str] = set()
    for candidate in (raw_emails or "").split(","):
        email = candidate.strip().lower()
        if email and email not in seen:
            emails.append(email)
            seen.add(email)
    return emails


def _build_unique_username(user_model, username_field: str, email: str) -> str:
    field = user_model._meta.get_field(username_field)
    max_length = getattr(field, "max_length", 150) or 150
    base_username = re.sub(r"[^a-z0-9._-]", "-", email.split("@", 1)[0].lower()).strip(
        "._-"
    )
    if not base_username:
        base_username = "admin"
    base_username = base_username[:max_length]
    candidate = base_username
    suffix = 1
    while user_model._default_manager.filter(**{username_field: candidate}).exists():
        suffix_text = f"-{suffix}"
        candidate = f"{base_username[: max_length - len(suffix_text)]}{suffix_text}"
        suffix += 1
    return candidate


def sync_admin_users_from_env() -> dict[str, int]:
    admin_emails = _parse_admin_user_emails(os.getenv("ADMIN_USER_EMAILS"))
    if not admin_emails:
        return {"created": 0, "updated": 0}

    from django.contrib.auth import get_user_model

    user_model = get_user_model()
    user_fields = {field.name for field in user_model._meta.fields}
    username_field = getattr(user_model, "USERNAME_FIELD", None)

    created_count = 0
    updated_count = 0

    for email in admin_emails:
        user = user_model._default_manager.filter(email__iexact=email).first()
        is_new_user = user is None
        changed_fields: set[str] = set()

        if is_new_user:
            create_kwargs = {}
            if "email" in user_fields:
                create_kwargs["email"] = email
            if (
                username_field
                and username_field != "email"
                and username_field in user_fields
            ):
                create_kwargs[username_field] = _build_unique_username(
                    user_model, username_field, email
                )
            user = user_model(**create_kwargs)
            user.set_unusable_password()
            changed_fields.update(create_kwargs.keys())

        if "email" in user_fields and (not user.email or user.email.lower() != email):
            user.email = email
            changed_fields.add("email")
        if hasattr(user, "is_active") and not user.is_active:
            user.is_active = True
            changed_fields.add("is_active")
        if hasattr(user, "is_staff") and not user.is_staff:
            user.is_staff = True
            changed_fields.add("is_staff")
        if hasattr(user, "is_superuser") and not user.is_superuser:
            user.is_superuser = True
            changed_fields.add("is_superuser")

        if is_new_user:
            user.save()
            created_count += 1
            logger.info("Created admin user from ADMIN_USER_EMAILS: %s", email)
        elif changed_fields:
            user.save(update_fields=sorted(changed_fields))
            updated_count += 1
            logger.info("Updated admin user from ADMIN_USER_EMAILS: %s", email)

    return {"created": created_count, "updated": updated_count}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/{{ docs_version }}/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "govuk.apps.GovukConfig",
    # "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.api.v2",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "govuk.middleware.AdminOIDCLoginMiddleware",
    "govuk.middleware.AuthenticatedUserRedirectMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_ONLY = True
ACCOUNT_ADAPTER = "govuk.adapters.AccountAdapter"
OIDC_PROVIDER_ID = os.getenv("OIDC_PROVIDER_ID", "internal-access")
OIDC_CLIENT_ID = os.getenv("OIDC_CLIENT_ID")
OIDC_ISSUER = os.getenv("OIDC_ISSUER", "https://sso.service.security.gov.uk")
OIDC_JWKS_URL = os.getenv(
    "OIDC_JWKS_URL", "https://sso.service.security.gov.uk/.well-known/jwks.json"
)
OIDC_END_SESSION_URL = os.getenv(
    "OIDC_END_SESSION_URL", "https://sso.service.security.gov.uk/sign-out"
)
OIDC_TOKEN_AUDIENCE = os.getenv("OIDC_TOKEN_AUDIENCE", OIDC_CLIENT_ID)
SOCIALACCOUNT_OPENID_CONNECT_URL_PREFIX = "oidc"
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        # Optional PKCE defaults to False, but may be required by your provider
        # Can be set globally, or per app (settings).
        "OAUTH_PKCE_ENABLED": False,
        "EMAIL_AUTHENTICATION": True,
        "APPS": [
            {
                "provider_id": "internal-access",
                "name": "Internal Access",
                "client_id": OIDC_CLIENT_ID,
                "secret": os.getenv("OIDC_CLIENT_SECRET"),
                "settings": {
                    # When enabled, an additional call to the userinfo
                    # endpoint takes place. The data returned is stored in
                    # `SocialAccount.extra_data`. When disabled, the (decoded) ID
                    # token payload is used instead.
                    "fetch_userinfo": True,
                    "oauth_pkce_enabled": False,
                    "server_url": "https://sso.service.security.gov.uk/.well-known/openid-configuration",
                    # Optional token endpoint authentication method.
                    # May be one of "client_secret_basic", "client_secret_post"
                    # If omitted, a method from the the server's
                    # token auth methods list is used
                    "token_auth_method": "client_secret_basic",
                    # The field to be used as the account ID.
                    "uid_field": "sub",
                },
            }
        ],
    }
}


def _bool_env(var_name: str, default: bool = False) -> bool:
    _var = os.getenv(var_name)
    if _var and len(_var) > 0 and _var.lower()[0] in ["t", "y", "1"]:
        return True
    return default


FEATURE_FLAGS = {
    "ORGANISATIONS": _bool_env("FEATURE_ORGANISATIONS"),
    "PEOPLE_FINDER": _bool_env("FEATURE_PEOPLE_FINDER"),
    "FEEDBACK": _bool_env("FEATURE_FEEDBACK"),
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

SIMPLE_JWT = {
    "ALGORITHM": "RS256",
    "JWK_URL": OIDC_JWKS_URL,
    "ISSUER": OIDC_ISSUER,
    "AUDIENCE": OIDC_TOKEN_AUDIENCE,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # OIDC ID tokens typically use "sub" as the subject identifier.
    "USER_ID_CLAIM": "sub",
    # OIDC ID tokens usually omit "jti", so do not require it.
    "JTI_CLAIM": None,
    # OIDC ID tokens do not include SimpleJWT's "token_type" claim.
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.UntypedToken",),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "govuk.authentication.InternalAccessJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

LOGIN_REDIRECT_URL = "/accounts/profile/"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/"
WAGTAILADMIN_LOGOUT_REDIRECT_URL = "/"

ROOT_URLCONF = "govuk.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "govuk.context_processors.navigation_and_breadcrumbs",
            ],
        },
    },
]

WSGI_APPLICATION = "govuk.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/{{ docs_version }}/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/{{ docs_version }}/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "govuk"
WAGTAIL_FRONTEND_LOGIN_URL = "/login/"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
# WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = [
    "csv",
    "docx",
    "key",
    "odt",
    "pdf",
    "pptx",
    "rtf",
    "txt",
    "xlsx",
    "zip",
]
