# Generated by Django 6.0.2 on 2026-02-18 12:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_convert_root_page_to_homepage"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional hero heading. If blank, the page title is used.",
                        max_length=255,
                    ),
                ),
                ("hero_intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "rows",
                    wagtail.fields.StreamField(
                        [("row", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional heading for this row section.",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": True},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ul", "ol"],
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("text", 2)]],
                                {"icon": "doc-full", "label": "Card"},
                            ),
                            4: (
                                "wagtail.blocks.ListBlock",
                                (3,),
                                {
                                    "help_text": "Add between 1 and 15 cards in this row section.",
                                    "max_num": 15,
                                    "min_num": 1,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("cards", 4)]],
                                {"icon": "placeholder", "label": "Row section"},
                            ),
                        },
                        help_text="Add one or more row sections. Each row section can contain up to 15 cards.",
                    ),
                ),
                ("free_text", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
