# Generated by Django 6.0.2 on 2026-02-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sectionpage_enable_combined_service_navigation_and_hero_styling'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Show phase banner across the site')),
                ('phase_label', models.CharField(default='Alpha', help_text='Label shown in the phase tag, for example Alpha or Beta.', max_length=20)),
                ('feedback_url', models.CharField(blank=True, default='', help_text='Feedback link URL, for example /feedback or https://example.gov.uk/feedback.', max_length=500)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
