# Generated by Django 6.0.2 on 2026-02-18 17:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contentpage_enable_combined_service_navigation_and_hero_styling_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use a relative URL like /cookies or an absolute URL like https://www.gov.uk/help.', 'max_length': 500, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1)]], {'icon': 'link', 'label': 'Footer link'})}, help_text='Links shown in the footer support links list.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
