# Generated by Django 6.0.2 on 2026-02-19 13:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_govuktag_alter_sectionpage_rows_contentpagetag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='rows',
            field=wagtail.fields.StreamField([('row', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading for this row section.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional button text.', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional URL for the button, for example /apply or https://example.gov.uk/apply.', 'max_length': 500, 'required': False}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.GovukTag',), {'required': False}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Optional tags for this card.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 2), ('link_text', 3), ('link_url', 4), ('tags', 6)]], {'icon': 'doc-full', 'label': 'Card'}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Add between 1 and 15 cards in this row.', 'max_num': 15, 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 8)]], {'icon': 'placeholder', 'label': 'Row section'})}, help_text='Add one or more row sections. Each row can contain up to 15 cards.'),
        ),
    ]
