# Generated by Django 6.0.2 on 2026-02-19 14:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_sectionpage_rows"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentDiscoverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content discovery",
                "verbose_name_plural": "Content discovery",
            },
        ),
        migrations.CreateModel(
            name="ContentDiscoverySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name for this source, for example Technology in government blog.",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Remote URL to discover content from, for example a sitemap, feed or API endpoint.",
                        max_length=500,
                    ),
                ),
                (
                    "default_tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        help_text="Optional tags to apply to discovered content from this source.",
                        related_name="content_discovery_sources",
                        to="home.govuktag",
                    ),
                ),
                (
                    "settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="home.contentdiscoverysettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExternalContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA256 hash of the URL.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Remote URL for the discovered content entry.",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this external content item.",
                        max_length=255,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Optional summary or excerpt."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional publication date from the source.",
                        null=True,
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hide this item from external content listings.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional source-specific metadata.",
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_content_items",
                        to="home.contentdiscoverysource",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags applied to this external content item.",
                        related_name="external_content_items",
                        to="home.govuktag",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "title", "url"],
            },
        ),
    ]
