# Generated by Django 6.0.2 on 2026-02-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contentdiscoverysettings_contentdiscoverysource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontentitem',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Optional created date from the source.', null=True),
        ),
        migrations.AddField(
            model_name='externalcontentitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Optional updated date from the source.', null=True),
        ),
    ]
